// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ZdXWz0obE9FTn2Q4Yp68ikRbA4bDRUw',
    appId: '1:238611365145:web:10db39afe9c5d91a8fd988',
    messagingSenderId: '238611365145',
    projectId: 'points-app-xyz',
    authDomain: 'points-app-xyz.firebaseapp.com',
    storageBucket: 'points-app-xyz.firebasestorage.app',
    measurementId: 'G-LG2T2X5T1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdrAd7dmhbD3E0-SjW0ceoI0ADC87pSiM',
    appId: '1:238611365145:android:8a161811670a95ae8fd988',
    messagingSenderId: '238611365145',
    projectId: 'points-app-xyz',
    storageBucket: 'points-app-xyz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFUpt2du34wE_2-ZFRi8-QG6tjKJiUUTk',
    appId: '1:238611365145:ios:f455164a46c355028fd988',
    messagingSenderId: '238611365145',
    projectId: 'points-app-xyz',
    storageBucket: 'points-app-xyz.firebasestorage.app',
    iosBundleId: 'com.points.iosapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFUpt2du34wE_2-ZFRi8-QG6tjKJiUUTk',
    appId: '1:238611365145:ios:97bef4457a2fd67a8fd988',
    messagingSenderId: '238611365145',
    projectId: 'points-app-xyz',
    storageBucket: 'points-app-xyz.firebasestorage.app',
    iosBundleId: 'com.points.macosapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2ZdXWz0obE9FTn2Q4Yp68ikRbA4bDRUw',
    appId: '1:238611365145:web:de857336a93d23508fd988',
    messagingSenderId: '238611365145',
    projectId: 'points-app-xyz',
    authDomain: 'points-app-xyz.firebaseapp.com',
    storageBucket: 'points-app-xyz.firebasestorage.app',
    measurementId: 'G-M33M5EM1J7',
  );
}
